# Generated by Django 5.1.4 on 2025-01-03 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_auth', '0003_profilebusiness_profilecustomer_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecustomer',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='uploads')),
                ('location', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('working_hours', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileBusiness',
        ),
        migrations.DeleteModel(
            name='ProfileCustomer',
        ),
    ]
