# Generated by Django 5.1.4 on 2025-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_auth', '0005_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
