# Generated by Django 5.1.4 on 2025-01-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_auth', '0007_profile_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coderr_auth.fileupload'),
        ),
    ]
